### ISSUE TITLE
Write example Cosmos snippets

### ISSUE THREAD

**Issue by frodopwns** [microsoft/helium#11]
Write (or copy, let's be real!) and manually test these example snippets in typescript:

- [x] database connection client instantiation
- [x] insert query
- [x] select query
- [x] update query
- [ ] delete query

These snippets should be pasted into comments on this issue. These snippets will be used to flesh out the REST api route controller functions later on.

**Comment by seushermsft** [comment]
Here are snippets to support the operations we currently support:

**Get All Movies:**

command: `curl -G 'localhost:3000/api/movies' | jq`
query: `SELECT * FROM c`

**Get Movie by Name (title):**

command: `curl -G 'localhost:3000/api/movies' --data-urlencode 'q=Nebeska udica' | jq`
query: `SELECT * FROM c where CONTAINS(c.title, "Nebeska udica")`

**Get Movie by Id:**

command: `curl -G localhost:3000/api/movies/tt0209180 | jq`
query: `SELECT * FROM c where c.movieId = "tt0209180"`

**Insert (or update) Movie:**

command: `curl -X POST 'localhost:3000/api/movies' -d '{ "id": "4", "title": "My Movie 4", "movieId": "movie4", "content": "created" }' -H "Content-Type: application/json"`
