### ISSUE TITLE
As a developer, I want to incorporate Helium app with Cobalt Infrastructure.

### ISSUE THREAD

**Issue by jred55** [microsoft/helium#116]
- Helium is a reference app built on Node.js
- Cobalt uses app service for containers to setup infrastructure best practices to deploy containerized applications. 

This epic involves incorporating Helium app with Cobalt infrastructure.

**Comment by frodopwns** [comment]
The infra for the Helium tests should be managed by Cobalt. At least for the WAC deployment. There should also be a version of Helium deployed to AKS via Bedrock.
