### ISSUE TITLE
As a developer, I want to add complexity to reference app to showcase CosmosDB best practices

### ISSUE THREAD

**Issue by jred55** [microsoft/helium#120]
- Add user and ratings 
- Add versioning for APIs (Ratings API v1 and v2)
- Provide best practices for data model

**Comment by frodopwns** [comment]
There is some question about how much complexity should be added. One person thought keeping it simple would make it easier for developers to clone this repo and use it as a starting point. Another person had the opinion that a more complex application would be a more realistic example.

I think I generally agree that keeping it simple makes sense if the goal is to use this project as a bootstrap. If it's more an example, then we could add more complexity, but it is hard to tell if it would add or detract value.

**Comment by frodopwns** [comment]
API Versioning might make sense. Don't think user ratings do anymore.
