### ISSUE TITLE
Allow users to delete movies

### ISSUE THREAD

**Issue by frodopwns** [microsoft/helium#151]
Add a context menu to Movie cards. Add a delete option to this menu.

When a user clicks this option, they should be prompted to confirm or cancel. If they confirm, send a DELETE request to /api/movies/[movie_id]

Note: This endpoint still needs to be implemented in the API

**Comment by frodopwns** [comment]
#148

**Comment by melonrush13** [comment]
- [X] Add Ellipsis button on Movie Card 
- [X] Create Pop on Menu on Movie Card, with a list item with "Delete"
- [ ] When "delete" List Item is clicked, delete movie using axios
- [ ] Make it look pretty :)
