### ISSUE TITLE
Remove Telemetry from cosmosdbprovider.ts to keep modules independent

### ISSUE THREAD

**Issue by jananivMS** [microsoft/helium#184]
We'll need to remove inclusion of telemetry provider in the cosmosdb provider. This also means we need to make sure we can do all logging and eventing from the caller, and that we don't lose any of the errors in the cosmos db module.

**Comment by frodopwns** [comment]
Sorry, I think this was based on bad advice from me. I forgot, for a moment, that these clients are actually just our wrappers of the 3rd party clients and not true packages that are mean t to be reused elsewhere.

In this case I think it's perfectly appropriate and a good idea to pass the logging and telemetry in. This will help keep the controller code easier to read.
