### ISSUE TITLE
Add ability to optionally log RU for cosmosDB interactions

### ISSUE THREAD

**Issue by frodopwns** [microsoft/helium#199]
This logging can add resource usage so it should be off by default.

Add a flag or request header that tells the app to log RUs when interacting with CosmosDB.

**Comment by frodopwns** [comment]
Determine if it actually costs extra to get the RU for a query.

**Comment by ericpera-msft** [comment]
It does not, the RU cost is returned by default in the response headers that come back from the Cosmos REST API.
