### ISSUE TITLE
Reduce duplication in controller methods

### ISSUE THREAD

**Issue by frodopwns** [microsoft/helium#219]
Right now, each endpoint controller has a start, time, stop time, and duration. This could potentially be handled in a decorator on the methods. It could also be improved by using Restify's pre and post hooks to send the metrics.

Once that has been done you may also be able to move other parts of the metrics calls there.

**Done**: A Solution has been identified to reduce the metrics-related duplication in endpoint controller methods. A Ticket has been created to implement that solution.

**Comment by aka-msft** [comment]
Currently investigating.  Comparing the use of JavaScript decorators vs. middleware functions in express/restify:

https://www.sitepoint.com/javascript-decorators-what-they-are/
http://expressjs.com/en/api.html#app.use
http://expressjs.com/en/api.html#middleware-callback-function-examples
http://expressjs.com/en/guide/using-middleware.html
