### ISSUE TITLE
Audit package.json to resolve vulnerabilities

### ISSUE THREAD

**Issue by aka-msft** [microsoft/helium#259]
https://github.com/microsoft/helium/blob/f2a91e450e7cc2896ee9cc1e6f1c1a9c710bd942/package.json#L57

`npm audit` on helium currently outputs several vulnerabilities.  Investigate which of these we can fix prior to finalizing v1.

In some cases, the audit provides commands to resolve the vulnerability, such as

`npm install --save-dev chai-http@4.3.0`
`npm update minimatch --depth 7`

**Comment by frodopwns** [comment]
All of the vulnerabilities that were listed were issues specific to our development use of the deps and not our production code.
