### ISSUE TITLE
Clean up server.ts file

### ISSUE THREAD

**Issue by aka-msft** [microsoft/helium#260]
https://github.com/microsoft/helium/blob/f2a91e450e7cc2896ee9cc1e6f1c1a9c710bd942/src/server.ts#L1

In server.ts

- Is it possible to extract or consolidate the long list of imports and bindings for ioc?
- Define constants in the same place rather than peppered throughout the code
- Capitalization in comments
- Unlikely case, but in getConfigValues we should handle if CLIENT_SECRET env var is set but CLIENT_ID isn't, and output that info to the user
- Extract getConfigValues and html out of server.ts if possible -> do they need to be located in this file?

**Comment by frodopwns** [comment]
clean up duplication in bindings

**Comment by frodopwns** [comment]
We should move as much of the swagger stuff out as possible. That means the html template for the most part.

**Comment by frodopwns** [comment]
Clean up the bindings if possible. If the solution isn't any better than the current situation, don't bother.
