### ISSUE TITLE
Merge config and dbconfig (currently separate files) into a single object

### ISSUE THREAD

**Issue by aka-msft** [microsoft/helium#312]
Unresolved comment from PR #309 :

Merge the contents of config.ts and dbconfig.ts into an object.  The object should initialize itself in the constructor using environment variables, and add other functions as needed to access keyvault for secrets.

**Comment by frodopwns** [comment]
End result of this ticket would be a ConfigService object that encapsulates the logic that gets config values from the local env.

**Comment by frodopwns** [comment]
I'm just going to close this one. It would clean up the config situation a bit, but it isn't really high value.
