### ISSUE TITLE
Searchable fields in CosmosDB should be lower-cased for indexed lookups

### ISSUE THREAD

**Issue by seushermsft** [Microsoft/helium#69]
Without forcing the case in the data storage, we have to use . case-modifiers in the query which will do database scans over using an index.

**Comment by bartr** [comment]
Sean and I discussed on IM and propose that we add a lower() search field to Movies and Actors and also update the IMDb queries to show and explain the difference. The RUs are significantly higher as you scale if you use lower().

Note that the genre ID is already lower() but the genre in the Movie document is proper case. For genre search, I run a query against genre with a lower() key and then use the returned value for the query to Movies.

We could add the genres to the search field (maybe "genre:action") and cut out a round trip. There's generally 1-3 genres, so it's not a lot of data. Thoughts?

Beyond a very small search, you would want to leverage AzSearch or SOLR but for small amounts of data, an index search in Cosmos is a good balance of simplicity, performance and cost.

Longer term, we should define "very small search".

**Comment by seushermsft** [comment]
The query was updated in #68 which has been merged. Closing this issue.
