### ISSUE TITLE
Create Demo UI to Expose Data from the API

### ISSUE THREAD

**Issue by seushermsft** [microsoft/helium#97]
We should have a UI that can talk to the Helium API.

The requirements are as follows (in this order):

1. Initially show all of the movie titles - sorted by rating.
2. Allow people to search for a movie by title.
3. Clicking on a movie title will display the full movie metadata and the actors (orders by `actor.order`).
4. Clicking on an actor will display the actor metadata.

**Comment by melonrush13** [comment]
![genresapiUI](https://user-images.githubusercontent.com/7874406/57238365-75bd1d00-6fe6-11e9-8f13-aee909d2ac95.png)

**Comment by melonrush13** [comment]
![Screen Shot 2019-05-08 at 2 37 15 PM](https://user-images.githubusercontent.com/7874406/57406832-f888d800-719e-11e9-9809-ae05f62f5d36.png)

**Comment by frodopwns** [comment]
Use material design, make each movie a card.

**Comment by frodopwns** [comment]
Lives here https://github.com/microsoft/helium-ui
